{{- if .Values.ingress.enabled -}}
{{- if .multiPodDeployment -}}
{{- $fullName := include "media-stack.fullname" . -}}-qbt-prowlarr
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.qbittorrent.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.qbittorrent.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "media-stack.labels" . | nindent 4 }}
    app: qbt-prowlarr
  {{- with .Values.qbittorrent.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  tls:
    {{- if .Values.qbittorrent.ingress.tls }}
    {{- with .Values.qbittorrent.ingress.tls }}
    - hosts:
        - {{ $.Values.qbittorrent.ingress.host | quote }}
      secretName: {{ .secretName }}
    {{- end }}
    {{- end }}
    {{- if .Values.prowlarr.ingress.tls }}
    {{- with .Values.prowlarr.ingress.tls }}
    - hosts:
        - {{ $.Values.prowlarr.ingress.host | quote }}
      secretName: {{ .secretName }}
    {{- end }}
    {{- end }}
  rules:
    {{- with .Values.qbittorrent.ingress }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ .servicePort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ .servicePort }}
              {{- end }}
          {{- end }}
    {{- end }}

    {{- with .Values.prowlarr.ingress }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ .servicePort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ .servicePort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
